### PR TITLE
[JENKINS-27734] Shelve any kind of item

### PR DESCRIPTION
**Pull request by PierreBtz**
Not only buildable ones (Freestyles, Pipelines) but also Folders
for instance.

NB only line 70 changed in `UnshelveProjectExecutable`, rest is due to a wrong (CRLF) line ending on the previous version.

CC @reviewbybees

### CODE REVIEW

**Comment by cpfeiffer** [comment]
What's the status of this? Shelving jobs and folders would greatly improve automatic job cleanup by the jobdsl plugin (automatically shelving unused jobs is a bit safer than automatically deleting them entirely...).

**Comment by PierreBtz** [comment]
@cpfeiffer I didn't have a heavily used Jenkins instance at hand to test well this change. The change itself allows to shelve almost anything so it's quite a big change, I'd really like to have it tested properly.

In case you are interested, I can refresh the PR, merge it and release a beta version of the plugin with the fix.

**Comment by cpfeiffer** [comment]
@PierreBtz that would be great! From looking at the code, I'm wondering if the changes to ShelveProjectTask (e.g. https://github.com/jenkinsci/shelve-project-plugin/pull/14/commits/07ba8803919e48b3f60fd5b9f7456ade55a699fc#diff-97084c54679364747fdb01425511447bR35 etc.) might have a negative effect. Maybe check for `instanceof BuildableItem` and return the proper results if `true`?

Besides that I could imagine issues with nested items, e.g. jobs nested in folders. "Someone" might need to take care that shelving a toplevel folder will not interfere the shelving of a nested job (if shelving can run concurrently, that is).

**Comment by PierreBtz** [comment]
@cpfeiffer I rebased the branch and followed your suggestion. Did some test and I'm happy. Once the CI build passes, I'll make an alpha release.

> Besides that I could imagine issues with nested items, e.g. jobs nested in folders. "Someone" might need to take care that shelving a toplevel folder will not interfere the shelving of a nested job (if shelving can run concurrently, that is).

That is a good point and something that indeed might happen. Something else is that there is currently no possible reconciliation if somebody unshelve a folder that would partially exist.

I feel I'm opening a door to potential conflicting situations here, that is why I'm releasing an alpha version of the plugin to collect more use cases before making the feature generally available.
At the moment I intend to warn people in the documentation about this release and those use cases  and work iteratively.

**Comment by PierreBtz** [comment]
Version 3.0-alpha-1 released in the experimental update center. See here to retrieve a plugin from it: https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/

**Comment by cpfeiffer** [comment]
Awesome, will try it!

**Comment by cpfeiffer** [comment]
My simple tests withs shelving and unshelving of projects and folders on different levels were successful. :+1:

**Comment by PierreBtz** [comment]
@cpfeiffer any extended feedback on real case usage of this feature? I'd like to cut a new official (non beta) release of the plugin with it, having some feedback would help me determine if the feature is safe enough.

**Comment by cpfeiffer** [comment]
Thanks for asking. We're using it successfully since then, without any issues at all. We don't (need to) unshelve often but everything we did was successful. So from my side this is a :+1:

**Comment by PierreBtz** [comment]
@cpfeiffer I just released version 3.0 with this new feature: https://github.com/jenkinsci/shelve-project-plugin/releases/tag/shelve-project-plugin-3.0

**Pull request merged**
